version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: habitflow-db
    environment:
      POSTGRES_DB: habitflow
      POSTGRES_USER: habitflow
      POSTGRES_PASSWORD: habitflow1234
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U habitflow"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    env_file:
      - .env
    build: .
    container_name: habitflow-backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://habitflow-db:5432/habitflow
      SPRING_DATASOURCE_USERNAME: habitflow
      SPRING_DATASOURCE_PASSWORD: habitflow1234
      SPRING_JPA_HIBERNATE_DDL-AUTO: update

volumes:
  postgres-data: