spring.application.name=habitflow

# These will use the environment variables directly
spring.datasource.url=jdbc:postgresql://postgres:5432/habitflow
spring.datasource.username=habitflow
spring.datasource.password=habitflow1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

springdoc.swagger-ui.path=/docs

spring.jwt.secret=a2e4e9b0f1d5b17a2d7c8f42b5e4ef8cf6a05f98d4efbda5d3ee9ccf3d7c6f6ec1a8d92879d3fc61a8b733b872adb66d8e8a889db6fd83f7b8d4ae4f3e9b4c01
spring.jwt.expiration=86400000

spring.ai.huggingface.api-key=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
